version: '3'

services:
  api:
    build: .
    container_name: ecommerce-api
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=sqlite:///./ecommerce.db
      - SECRET_KEY=production_secret_key_change_me
    restart: always 